### PR TITLE
Font optimization

### PR DESCRIPTION
**Pull request by GMSoudersJr**
### Getting fonts to display properly
Updated Next to allow for `import { font } from 'next/font/google';` 
fCC Font Update

There were no breaking changes on my end. I did notice two warnings server-side about:
- image.domains
- react-i18next

I will approach them in a different commit.

### Fonts
I chose these because they are variable fonts.

P.S. Did I mess up the history some how? If so, the font update was not difficult to implement. I can start over.

### CODE REVIEW

**Comment by ivanms1** [comment]
> P.S. Did I mess up the history some how? If so, the font update was not difficult to implement. I can start over.

It's ok in our case, everything will be squashed in one nice commit once we merge.
[Like your last PR](https://github.com/Free-Code-Camp-Seoul/fcc-seoul-website/commits/master/)

**Review by ivanms1 — COMMENTED** [review]
Great job!

I just realized we don't have any tags (main, div, etc) in the `_app.tsx` file, probably not ideal.
Would it be possible to move the font injection to the `Layout` component?
So that we can use the className approach which I think it's cleaner.

Something like this
```jsx
// ...other stuff
import { inter } from "pages/fonts";
// ... other stuff

const Layout = ({ children }: LayoutProps) => {
  return (
    <main className={`${styles.Layout} ${inter.className}`}>
      <Navbar />
      <div className={styles.Content}>{children}</div>
      <Footer />
    </main>
  );
};

export default Layout;
```

another thing, could we use Poppins intead of Inter?
To mantain the original font
```js
export const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
  style: ["normal"],
  variable: "--font-poppins",
});
```
Lastly, feel free to remove the `<></>` tag in `_app.tsx`, it's not really doing anything.

**Comment by ivanms1** [comment]
I forgot to mention, thanks for updating the next js version.
I am surprised there were no breaking changes.
I ran the app locally and I didn't notice any warnings, so I think we are all good.

**Comment by GMSoudersJr** [comment]
Thanks!

Updated files accordingly.

I noticed that the i18n warning went away without changing anything.

Thanks for the tips on the font injection.

**Review by ivanms1 — APPROVED** [review]
LGTM!

**Pull request merged**
